// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtcPM6aO6kmvbb28N16FQkYCAauwtsODU',
    appId: '1:818017615522:web:3c8f1b472b9263a4bfa1fb',
    messagingSenderId: '818017615522',
    projectId: 'senior-project-d8035',
    authDomain: 'senior-project-d8035.firebaseapp.com',
    storageBucket: 'senior-project-d8035.appspot.com',
    measurementId: 'G-W6D0WG5TN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDWWM-OQmI0cbkomKTwWpPk-1ZQWznBs',
    appId: '1:818017615522:android:0d0efff6c2a8266ebfa1fb',
    messagingSenderId: '818017615522',
    projectId: 'senior-project-d8035',
    storageBucket: 'senior-project-d8035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1eO37nYKzDn7jqAovlhovs-aO8JWEUxo',
    appId: '1:818017615522:ios:397f73db5900eb28bfa1fb',
    messagingSenderId: '818017615522',
    projectId: 'senior-project-d8035',
    storageBucket: 'senior-project-d8035.appspot.com',
    iosClientId: '818017615522-dl52nmtp7cboraq4hh4qhbjpv2nbkqv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.seniorprojectdemo',
  );
}
